### ISSUE TITLE
Phase 2 will sometimes generate the back of card where front is expected

### ISSUE THREAD

**Issue by Mcghee-Jake** [team-makeSmart/GUI-Cards#19]
I didn't realize this at first but if you run the program enough times, the backs of the card will be generated in place of where the front is expected. (for example, in the players hand or in the playing area)

**Comment by p12345vls** [comment]
I placed a comment there: " should the back card be the in the last index of the array?" So the answer is no. We can just assign it directly to the  iconBack, for example
  **iconBack = new ImageIcon("src/images/BK.gif");**

**Comment by hmason55** [comment]
Yeah so I was able to replicate this result and it happens when GUICard.getIcon tries to get an Ace of Spades instead it displays the card back. This is probably due to some offset in the array index upon retrieval.

**Comment by hmason55** [comment]
To fix this I've just manually assigned iconBack instead of adding the card back to the icon array:

From
`iconCards[NR_OF_VALUES-1][NR_OF_SUITS-1]  = new ImageIcon(inputFileName+"BK"+fileExtension);`
`iconBack = [NR_OF_VALUES-1][NR_OF_SUITS-1];`

To this:
`iconBack = new ImageIcon(inputFileName+"BK"+fileExtension);`
